apiVersion: v1
kind: Service   # Service definition file will be based on application.properties file
metadata:
  name: vprodb
spec:
  ports:    
    - port: 3306      # Need port name if vprodbdep.yaml ports: - name: vprodb-port
      targetPort: vprodb-port
      protocol: TCP   # Accept the request on port 3306
  selector:           # Send the request to the backend pod (vprodb) on port 3306
    app: vprodb