apiVersion: v1  # Service definition file for vprodbdep.yaml (Deployment file)
kind: Service   # Service definition file will be based on application.properties file
metadata:
  name: vprodb
spec:
  ports:                      # Need port name in vprodbdep.yaml Sports: - name: vprodb-port
    - port: 3306              # Accept the request on port 3306 
      targetPort: vprodb-port # vprodbdep.yaml ports: - name: vpromc-port containerPort: 11211
      protocol: TCP   
  selector:                   # Forward the request to the backend pod (vprodb) on port 3306
    app: vprodb
  type: ClusterIP