apiVersion: v1  # Service definition file for mcdep.yaml (Deployment file)
kind: Service   # Service definition file will be based on application.properties file
metadata: 
  name: vprocache01
spec: 
  ports:                        # Need port name in mcdep.yaml ports: - name: vpromc-port
    - port: 11211               # Listen for requests on port 11211
      targetPort: vpromc-port   # mcdep.yaml ports: - name: vpromc-port containerPort: 11211
      protocol:
  selector:                     # Forward the request to ClusterIP
    app: vpromc
  type: ClusterIP