apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port
  selector:
    app: vproapp
  type: LoadBalancer  # Launch an Elastic Load Balancer